info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    enabled: true
    serviceUrl:
       defaultZone: http://myallrounddata-eureka.timmygilissen.svc.tutum.io:8761/eureka/


spring:
  cloud:
    config:
        uri: http://myallrounddata-config.timmygilissen.svc.tutum.io:7777/

zuul:
  routes:
    user-service: /u/**

server:
  port: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG